---
- name: reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart taskflow-frontend
  ansible.builtin.systemd:
    name: taskflow-frontend
    state: restarted

- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
