apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskflow-frontend
  namespace: devops-app
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: taskflow
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskflow-backend
  namespace: devops-app
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: taskflow
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskflow-worker
  namespace: devops-app
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: taskflow
automountServiceAccountToken: false
